name: CI - .NET Tests with Chrome

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOTNET_ROOT: /usr/share/dotnet

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Create appsettings.json from secrets
        run: |
          mkdir -p logs
          echo "{
            \"LOGIN\": \"${{ secrets.TEST_LOGIN }}\",
            \"PASSWORD\": \"${{ secrets.TEST_PASSWORD }}\",
            \"Serilog\": {
              \"Using\": [\"Serilog.Sinks.Console\", \"Serilog.Sinks.File\"],
              \"MinimumLevel\": {
                \"Default\": \"Information\",
                \"Override\": {
                  \"Microsoft\": \"Warning\",
                  \"System\": \"Warning\"
                }
              },
              \"WriteTo\": [
                {
                  \"Name\": \"Console\"
                },
                {
                  \"Name\": \"File\",
                  \"Args\": {
                    \"path\": \"${{ github.workspace }}/logs/logfile.log\",
                    \"restrictedToMinimumLevel\": \"Information\"
                  }
                }
              ]
            }
          }" > appsettings.json

      - name: Run tests
        run: dotnet test --configuration Release --logger "console;verbosity=detailed" --logger "trx;LogFileName=test-results.trx"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs/logfile.log

      - name: List Release folder
        run: ls -lah ./bin/Release/net8.0/

      - name: Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: ./bin/Release/net8.0/index.html